# Generated by Django 5.0.6 on 2024-05-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("manager", "0001_initial"),
        ("staff", "0001_initial"),
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "request_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reply", models.CharField(max_length=200)),
                ("typ", models.CharField(max_length=30)),
                ("manager_ID", models.ManyToManyField(to="manager.manager")),
                (
                    "staff_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
                (
                    "tour_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.tour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_draft", models.TextField(default="No data")),
                ("edit_info", models.CharField(max_length=200, null=True)),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requestTour.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(default="No reason")),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requestTour.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(default="Default Tour Name", max_length=1000),
                ),
                ("departure", models.CharField(max_length=50)),
                ("vehicle", models.TextField()),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField()),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("schedule", models.TextField(default="Tour Schedule")),
                ("service", models.TextField(default="Tour Service")),
                ("places", models.ManyToManyField(to="tour.place")),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requestTour.request",
                    ),
                ),
            ],
        ),
    ]
