# Generated by Django 5.0.6 on 2024-06-02 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requestTour", "0003_request_is_duplicate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="is_duplicate",
        ),
    ]
