# Generated by Django 5.0.6 on 2024-05-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("province", models.TextField()),
                ("description", models.TextField(default="No information")),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PlaceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.URLField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "place_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tour.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "tour_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.TextField(default="Default Tour Name", max_length=1000),
                ),
                ("departure", models.CharField(max_length=50)),
                ("vehicle", models.TextField()),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField(default=False)),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("schedule", models.TextField(default="Tour Schedule")),
                ("service", models.TextField(default="Tour Service")),
                ("is_cancel", models.BooleanField(default=False)),
                ("places", models.ManyToManyField(to="tour.place")),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.staff",
                    ),
                ),
            ],
        ),
    ]
