# Generated by Django 5.0.6 on 2024-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="tour_description",
            field=models.TextField(null=True),
        ),
    ]
