# Generated by Django 5.0.6 on 2024-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0002_tour_tour_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="note",
            field=models.TextField(null=True),
        ),
    ]
