# Generated by Django 5.0.6 on 2024-05-14 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=10)),
                ("dateOfBirth", models.DateField()),
                ("isActive", models.BooleanField(default=True)),
                ("gender", models.CharField(max_length=3)),
                ("lastName", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100)),
                ("encryp_pass", models.CharField(max_length=50)),
                ("firstLogin", models.BooleanField(default=True)),
                ("managerID", models.ManyToManyField(to="manager.manager")),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
