# Generated by Django 5.0.6 on 2024-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="encryp_pass",
            field=models.CharField(default="123456", max_length=50),
        ),
    ]
