# Generated by Django 5.0.6 on 2024-05-14 04:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("province", models.TextField()),
                ("description", models.TextField(default="No information")),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=50, unique=True)),
                ("forget_password_token", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("phone_no", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "manager_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("pay_method", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=30)),
                ("phone_no", models.CharField(max_length=10)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(max_length=200)),
                ("ticket_num", models.IntegerField(default=1)),
                ("cancel_percent", models.IntegerField(default=0)),
                ("cancel_datetime", models.DateTimeField(null=True)),
                ("is_cancel", models.BooleanField(default=False)),
                ("is_refund", models.BooleanField(default=False)),
                (
                    "user_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_feedback.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "feedback_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "ratings",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1),
                            django.core.validators.MaxValueValidator(limit_value=5),
                        ]
                    ),
                ),
                ("reviews", models.CharField(blank=True, max_length=200)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("tour_ID", models.CharField(max_length=20)),
                (
                    "user_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.customer",
                    ),
                ),
                (
                    "order_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer_views_Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.customer",
                    ),
                ),
                (
                    "place_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.URLField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "place_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="order_feedback.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "request_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reply", models.CharField(max_length=200)),
                ("typ", models.CharField(max_length=30)),
                ("manager_ID", models.ManyToManyField(to="order_feedback.manager")),
            ],
        ),
        migrations.CreateModel(
            name="EditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_draft", models.TextField(default="No data")),
                ("edit_info", models.CharField(max_length=200, null=True)),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(default="No reason")),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(default="Default Tour Name", max_length=1000),
                ),
                ("departure", models.CharField(max_length=50)),
                ("vehicle", models.TextField()),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField()),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("schedule", models.TextField(default="Tour Schedule")),
                ("service", models.TextField(default="Tour Service")),
                ("places", models.ManyToManyField(to="order_feedback.place")),
                (
                    "request_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_feedback.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=10)),
                ("dateOfBirth", models.DateField()),
                ("isActive", models.BooleanField(default=True)),
                ("gender", models.CharField(max_length=3)),
                ("lastName", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100)),
                ("encryp_pass", models.CharField(max_length=50)),
                ("firstLogin", models.BooleanField(default=True)),
                ("managerID", models.ManyToManyField(to="order_feedback.manager")),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="staff_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order_feedback.staff"
            ),
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "tour_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.TextField(default="Default Tour Name", max_length=1000),
                ),
                ("departure", models.CharField(max_length=50)),
                ("vehicle", models.TextField()),
                ("seat_num", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("isActive", models.BooleanField(default=False)),
                ("starting_date", models.DateField()),
                ("bookingDeadline", models.DateField()),
                ("day_num", models.IntegerField()),
                ("night_num", models.IntegerField()),
                ("note", models.CharField(max_length=100)),
                ("schedule", models.TextField(default="Tour Schedule")),
                ("service", models.TextField(default="Tour Service")),
                ("is_cancel", models.BooleanField(default=False)),
                ("places", models.ManyToManyField(to="order_feedback.place")),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_feedback.staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="tour_ID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order_feedback.tour",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tour_ID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order_feedback.tour",
            ),
        ),
    ]
