# Generated by Django 5.0.6 on 2024-05-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_feedback', '0002_remove_addrequest_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tour_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(max_length=50),
        ),
    ]
