# Generated by Django 5.0.6 on 2024-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_feedback", "0004_order_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.TextField(null=True),
        ),
    ]
